from pathlib import Path
import csv
import re
import sys
from typing import Iterable

import yaml

###############################################################################
# BASELINE CONFIGURATION
#
# Edit this YAML block to change the baseline support files generated by this
# script. Chart variables are configured with variable name prefixes plus
# selectors only. Do not put full variable names such as GDPR(USA) here.
###############################################################################

BASELINE_CONFIGURATION_YAML: str = """
baseline:
  model_configuration_file_name: configuration.csv
  overwrite_generated_files: true
files:
  readme_file_name: README.md
  documentation_file_name: documentation.md
  chartpack_file_name: chartpack.csv
  run_script_file_name: run_baseline.py
chartpack:
  title: Baseline
  first_result_year:
  last_result_year:
  charts:
    - variable_prefix: INFL
      selectors:
        regions: all
    - variable_prefix: GDPRGROWTH
      selectors:
        regions: all
    - variable_prefix: GDPR
      selectors:
        regions: all
    - variable_prefix: INTN
      selectors:
        regions: all
    - variable_prefix: INTR
      selectors:
        regions: all
    - variable_prefix: EXCH
      selectors:
        regions: all
    - variable_prefix: NEER
      selectors:
        regions: all
    - variable_prefix: BOND
      selectors:
        regions: all

run_baseline:
  force_model_to_resolve: true
  show_baseline_charts: true
  solved_model_file_name: solved_model.joblib
  derivations:
    - GDPRGROWTH
"""

###############################################################################
# IMPLEMENTATION
# Ordinary baseline changes should be made in the YAML block above.
###############################################################################

README_TEMPLATE: str = """# Baseline

This folder contains the script to set up the baseline projections.

Configure and then run the setup_baseline.py script first. That will produce a tailored 
run_baseline.py script which will generate the baseline projections when run.  It will also produce
the other artefacts required to run and report on the baseline.

To configure the setup for the baseline, edit the YAML block at the top of the setup_baseline.py script. 
This includes the configuration of the baseline chartpack, which determines the charts included in the 
baseline report and the variables included in those charts. See the [instructions](INSTRUCTIONS.md) 
with details on how to configure the chartpack from the baseline setup script.

The run_baseline.py script will generate a report for the baseline projections. **It will also solve
the model and save the solved model to a joblib file in the results folder. This allows you to 
reuse the solved model for faster iteration on the baseline projections without needing to 
re-solve the model each time.**

You can change configuration settings in the run_baseline.py script.

You can also directly modify the chartpack that defines the baseline projections reports.

View [the detailed documentation for the baseline projections](documentation.md).
"""

DOCUMENTATION_TEMPLATE: str = """The baseline projections.\n"""

RUN_BASELINE_TEMPLATE: str = """###############################################################################
# User specified variables to determine baseline generation behavior.
###############################################################################

# Specify the model configuration file name.
model_configuration_file_name: str = \"{model_configuration_file_name}\"

# Solved model file name. This is the only joblib file written by this script.
solved_model_file_name: str = \"{solved_model_file_name}\"

# Set to true if you want to force the model to be solved again.
# This needs to be done if the data, parameters or SYM files change.
force_model_to_resolve: bool = {force_model_to_resolve}

# Set to true if you want to see the baseline charts web page when the script finishes.
show_baseline_charts: bool = {show_baseline_charts}

# Derived-variable definitions to include in reporting.
derivation_names: list[str] = {derivation_names!r}

#############################################################################
# Baseline customisation typically ends here.
#
# This script lives in simulations/baseline and writes results to
# results/<version>/<build>/baseline.
###############################################################################

from pathlib import Path
import sys
import pickle
import logging

from joblib import dump, load

# Resolve paths from this script's location in the simulation folder.
experiment_directory_path: Path = Path(__file__).resolve().parent
simulations_directory_path: Path = experiment_directory_path.parent
model_directory_path: Path = simulations_directory_path.parent
model_python_directory_path: Path = model_directory_path / \"python\"
model_configuration_file_path: Path = model_directory_path / model_configuration_file_name
root_results_directory_path: Path = model_directory_path.parent.parent / \"results\"
experiment_directory_name: str = experiment_directory_path.name

if str(model_python_directory_path) not in sys.path:
    sys.path.insert(0, str(model_python_directory_path))

from gcubed.model import Model
from gcubed.projections.baseline_projections import BaselineProjections
from gcubed.linearisation.solved_model import SolvedModel
from gcubed.model_configuration import ModelConfiguration
from gcubed import configure_logging
from gcubed.reporting import generate_all_simulation_results
from gcubed.derivations import create_derivations

# Check that the model configuration file exists.
assert (
    model_configuration_file_path.exists()
), f\"Model configuration file not found at {{model_configuration_file_path}}\"

# Load the model configuration.
model_configuration: ModelConfiguration = ModelConfiguration(
    configuration_file=model_configuration_file_path
)

# Save this baseline run to results/<version>/<build>/baseline.
results_folder: Path = (
    root_results_directory_path
    / model_configuration.version
    / model_configuration.build
    / experiment_directory_name
)
results_folder.mkdir(parents=True, exist_ok=True)

# Set up logging.
configure_logging(folder=results_folder)

# Load or solve the model, then regenerate baseline projections in memory.
solved_model_file: Path = results_folder / solved_model_file_name

if not force_model_to_resolve and solved_model_file.exists():
    logging.warning(f\"!!! Loading previously solved model from {{solved_model_file}}\")
    with open(solved_model_file, \"rb\") as file:
        solved_model: SolvedModel = load(file)
else:
    model: Model = Model(configuration=model_configuration)
    solved_model: SolvedModel = SolvedModel(model=model)
    with open(solved_model_file, \"wb\") as file:
        logging.info(\"Serialising the solved model\")
        dump(
            solved_model,
            file,
            compress=(\"zlib\", 0),
            protocol=pickle.HIGHEST_PROTOCOL,
        )
    logging.info(
        f\"Saved the solved model for later reuse. Run again with the force_model_to_resolve flag set to True if required.\"
    )

baseline_projections: BaselineProjections = BaselineProjections(
    solved_model=solved_model,
)

# Save the baseline projections to CSV files.
baseline_projections.charting_projections.to_csv(
    results_folder / \"baseline charting projections.csv\"
)

baseline_projections.database_projections.to_csv(
    results_folder / \"baseline database projections.csv\"
)

derivations = create_derivations(derivation_names)

generate_all_simulation_results(
    chartpack_path=experiment_directory_path / \"chartpack.csv\",
    documentation_path=experiment_directory_path / \"documentation.md\",
    template_path=model_directory_path / 'templates' / \"chart-template.html\",
    results_directory_path=results_folder,
    derivations=derivations,
    all_projections=[baseline_projections],
    show_final_results=show_baseline_charts,
)
"""

DERIVED_REGION_PREFIXES: set[str] = {"GDPRGROWTH"}
REQUIRED_CONFIGURATION_SECTIONS: tuple[str, ...] = (
    "baseline",
    "files",
    "chartpack",
    "run_baseline",
)


def load_baseline_configuration() -> dict:
    configuration = yaml.safe_load(BASELINE_CONFIGURATION_YAML)
    assert isinstance(configuration, dict), "The baseline configuration YAML must parse to a mapping."
    missing_sections = [
        section
        for section in REQUIRED_CONFIGURATION_SECTIONS
        if section not in configuration
    ]
    assert not missing_sections, f"Missing YAML sections: {missing_sections}"
    return configuration


def require_prefix_only(variable_prefix: str) -> None:
    assert variable_prefix, "Each chart series must specify a variable_prefix."
    assert "(" not in variable_prefix and ")" not in variable_prefix, (
        "Chartpack configuration must use variable name prefixes only, "
        f"not full variable names: {variable_prefix}"
    )


def selected_members(selector_value, all_members: list[str]) -> list[str]:
    if selector_value is None or selector_value == "all":
        return list(all_members)
    if isinstance(selector_value, str):
        selector_value = [selector_value]
    result = list(selector_value)
    invalid = sorted(set(result) - set(all_members))
    assert not invalid, f"Unknown selector members {invalid}; valid members are {all_members}"
    return result


def variable_arguments(variable_name: str) -> list[str]:
    match = re.match(r"^[^(]+(?:\((.*)\))?$", variable_name)
    if match is None or match.group(1) is None or match.group(1) == "":
        return []
    return [part.strip() for part in match.group(1).split(",")]


def variable_matches_selectors(variable_name: str, selectors: dict, sym_data) -> bool:
    args = variable_arguments(variable_name)
    regions = selected_members(selectors.get("regions"), sym_data.regions_members)
    sectors = selected_members(selectors.get("sectors"), sym_data.sectors_members)
    goods = selected_members(selectors.get("goods"), sym_data.goods_members)

    if "regions" in selectors and not any(region in args for region in regions):
        return False
    if "sectors" in selectors and not any(sector in args for sector in sectors):
        return False
    if "goods" in selectors and not any(good in args for good in goods):
        return False
    return True


def derived_region_variables(variable_prefix: str, selectors: dict, sym_data) -> list[str]:
    regions = selected_members(selectors.get("regions"), sym_data.regions_members)
    return [f"{variable_prefix}({region})" for region in regions]


def resolve_series(chart_series: dict, sym_data) -> list[str]:
    variable_prefix = chart_series["variable_prefix"]
    selectors = chart_series.get("selectors", {})
    require_prefix_only(variable_prefix)

    if sym_data.has_variables_with_prefix(variable_prefix):
        variables = sym_data.variables_with_prefix(variable_prefix)
        result = [
            variable
            for variable in variables
            if variable_matches_selectors(variable, selectors, sym_data)
        ]
    elif variable_prefix in DERIVED_REGION_PREFIXES:
        result = derived_region_variables(variable_prefix, selectors, sym_data)
    else:
        raise AssertionError(
            f"The model does not include variables with prefix {variable_prefix}."
        )

    assert result, f"No chart variables resolved for {chart_series}"
    return result


def pack_attributes(chartpack_config: dict) -> str:
    attributes: list[str] = []
    first_year = chartpack_config.get("first_result_year")
    last_year = chartpack_config.get("last_result_year")
    if first_year is not None:
        attributes.append(f"start_year={first_year}")
    if last_year is not None:
        attributes.append(f"end_year={last_year}")
    return "|".join(attributes)


def chartpack_rows(chartpack_config: dict, sym_data) -> list[list[str]]:
    rows: list[list[str]] = [["type", "attributes", "variable", "label"]]
    rows.append(["pack", pack_attributes(chartpack_config), "", chartpack_config["title"]])

    for chart in chartpack_config["charts"]:
        rows.append(["chart", "", "", ""])
        series_definitions = chart.get("series")
        if series_definitions is None:
            series_definitions = [chart]
        for series_definition in series_definitions:
            for variable in resolve_series(series_definition, sym_data):
                rows.append(["series", "", variable, ""])
    return rows


def write_text(path: Path, text: str, overwrite: bool) -> None:
    if path.exists() and not overwrite:
        raise FileExistsError(f"Refusing to overwrite existing file: {path}")
    path.write_text(text)


def write_csv(path: Path, rows: Iterable[list[str]], overwrite: bool) -> None:
    if path.exists() and not overwrite:
        raise FileExistsError(f"Refusing to overwrite existing file: {path}")
    with path.open("w", newline="") as file:
        writer = csv.writer(file)
        writer.writerows(rows)


def main() -> None:
    configuration = load_baseline_configuration()
    baseline_config = configuration["baseline"]
    files = configuration["files"]
    run_config = configuration["run_baseline"]

    baseline_directory_path: Path = Path(__file__).resolve().parent
    simulations_directory_path: Path = baseline_directory_path.parent
    model_directory_path: Path = simulations_directory_path.parent
    model_python_directory_path: Path = model_directory_path / "python"
    model_configuration_file_path: Path = (
        model_directory_path / baseline_config["model_configuration_file_name"]
    )

    assert baseline_directory_path.name == "baseline", (
        "setup_baseline.py is expected to live in simulations/baseline."
    )
    assert model_configuration_file_path.exists(), (
        f"Model configuration file not found at {model_configuration_file_path}"
    )

    if str(model_python_directory_path) not in sys.path:
        sys.path.insert(0, str(model_python_directory_path))

    from gcubed.model import Model
    from gcubed.model_configuration import ModelConfiguration

    model_configuration = ModelConfiguration(configuration_file=model_configuration_file_path)
    model = Model(configuration=model_configuration)
    sym_data = model.sym_data

    overwrite = bool(baseline_config["overwrite_generated_files"])

    write_text(
        baseline_directory_path / files["readme_file_name"],
        README_TEMPLATE,
        overwrite=overwrite,
    )
    write_text(
        baseline_directory_path / files["documentation_file_name"],
        DOCUMENTATION_TEMPLATE,
        overwrite=overwrite,
    )
    write_csv(
        baseline_directory_path / files["chartpack_file_name"],
        chartpack_rows(configuration["chartpack"], sym_data),
        overwrite=overwrite,
    )
    write_text(
        baseline_directory_path / files["run_script_file_name"],
        RUN_BASELINE_TEMPLATE.format(
            model_configuration_file_name=baseline_config["model_configuration_file_name"],
            solved_model_file_name=run_config["solved_model_file_name"],
            force_model_to_resolve=run_config["force_model_to_resolve"],
            show_baseline_charts=run_config["show_baseline_charts"],
            derivation_names=run_config.get("derivations", []),
        ),
        overwrite=overwrite,
    )


if __name__ == "__main__":
    main()
