"""Run the model baseline simulation.

Purpose
-------
Load or solve the selected model, construct its baseline projections, save
the baseline data, and generate the configured report.

Archetype
---------
Baseline command. It does not apply an experiment simulation layer.

Client-owned inputs
-------------------
The configuration constants below select the model, solved-model cache,
reporting resources, derivations, and immediate run behaviour.

Setup-generated inputs
----------------------
The chartpack may be generated by setup or maintained manually. setup.py
and setup.yaml are not required to run this command.

Outputs
-------
The results folder receives run.log, the solved model when solving is
required, baseline projection CSVs, projection data, and HTML reports.

Workflow
--------
Create results and logging, load or solve the model, create derivations,
construct and save baseline projections, and generate results.

Run
---
Run ``python run_baseline.py`` from any working directory.

Rerun and mutation behaviour
----------------------------
A cached solved model is reused unless FORCE_MODEL_TO_RESOLVE is true.
Solving replaces the configured solved-model file. Reporting replaces
same-named result files but does not modify simulation source inputs.
"""

from __future__ import annotations

import logging
from pathlib import Path
import pickle
import sys

from joblib import dump, load

from gcubed import configure_logging
from gcubed.derivations import create_derivations
from gcubed.linearisation.solved_model import SolvedModel
from gcubed.model import Model
from gcubed.model_configuration import ModelConfiguration
from gcubed.projections.baseline_projections import BaselineProjections
from gcubed.reporting import generate_all_simulation_results


# =============================================================================
# CLIENT CONFIGURATION
# =============================================================================

# Model resources
SCRIPT_FOLDER: Path = Path(__file__).resolve().parent
MODEL_FOLDER: Path = SCRIPT_FOLDER.parent.parent
MODEL_CONFIGURATION_FILE: Path = MODEL_FOLDER / 'model_configuration.yaml'

# Experiment resources
CHARTPACK_FILES: tuple[str, ...] = ('chartpack.yaml',)
DOCUMENTATION_FILE: Path = SCRIPT_FOLDER / 'documentation.md'
REPORT_TEMPLATE_FILE: Path = MODEL_FOLDER / "templates" / 'chart-template-2.0.html'

# Results
# Results are rooted at results/<version>/<build>/baseline.
MODEL_RESULTS_FOLDER: Path = (
    MODEL_FOLDER.parent.parent
    / "results"
    / MODEL_FOLDER.parent.name
    / MODEL_FOLDER.name
)
RESULTS_FOLDER: Path = MODEL_RESULTS_FOLDER / SCRIPT_FOLDER.name
SOLVED_MODEL_FILE: Path = RESULTS_FOLDER / 'solved_model.joblib'

# Run options
# True always solves and replaces SOLVED_MODEL_FILE. False reuses it when
# present and solves only when no reusable file exists.
FORCE_MODEL_TO_RESOLVE: bool = True
# True opens each generated report in a browser; False only writes results.
SHOW_FINAL_RESULTS: bool = True

# Derived variables
# These names create one derivation collection shared by projections and
# reporting. An empty tuple disables derived-variable calculation.
DERIVATION_NAMES: tuple[str, ...] = ('GDPRGROWTH',)


def main() -> None:
    """Run the complete baseline workflow in execution order."""
    RESULTS_FOLDER.mkdir(parents=True, exist_ok=True)
    configure_logging(folder=RESULTS_FOLDER)
    logger = logging.getLogger(__name__)

    logger.info("Loading the model configuration")
    model_configuration = load_model_configuration()

    logger.info("Loading or solving the model")
    solved_model = load_or_solve_model(model_configuration)

    logger.info("Creating derived variables")
    derivations = create_derivations(DERIVATION_NAMES)

    logger.info("Constructing baseline projections")
    baseline_projections = BaselineProjections(solved_model=solved_model)

    logger.info("Persisting named baseline projections")
    save_baseline_projections(baseline_projections)

    logger.info("Generating baseline results")
    for chartpack_file_name in CHARTPACK_FILES:
        generate_all_simulation_results(
            chartpack_path=SCRIPT_FOLDER / chartpack_file_name,
            documentation_path=DOCUMENTATION_FILE,
            template_path=REPORT_TEMPLATE_FILE,
            results_directory_path=RESULTS_FOLDER,
            all_projections=[baseline_projections],
            derivations=derivations,
            show_final_results=SHOW_FINAL_RESULTS,
        )

    logger.info("Baseline run completed successfully")


# =============================================================================
# MODEL LOADING OR SOLVING
# =============================================================================

def load_model_configuration() -> ModelConfiguration:
    """Load the selected model configuration and local model Python path."""
    if not MODEL_CONFIGURATION_FILE.is_file():
        raise FileNotFoundError(
            f"Model configuration not found: {MODEL_CONFIGURATION_FILE}"
        )
    configuration = ModelConfiguration(
        configuration_file=MODEL_CONFIGURATION_FILE
    )
    python_folder = configuration.python_directory
    if str(python_folder) not in sys.path:
        sys.path.insert(0, str(python_folder))
    return configuration


def load_or_solve_model(
    model_configuration: ModelConfiguration,
) -> SolvedModel:
    """Reuse the solved model unless this run visibly requires solving."""
    if SOLVED_MODEL_FILE.is_file() and not FORCE_MODEL_TO_RESOLVE:
        logging.getLogger(__name__).warning(
            "Loading the solved model from %s", SOLVED_MODEL_FILE
        )
        with SOLVED_MODEL_FILE.open("rb") as file:
            return load(file)

    solved_model = SolvedModel(model=Model(configuration=model_configuration))
    SOLVED_MODEL_FILE.parent.mkdir(parents=True, exist_ok=True)
    with SOLVED_MODEL_FILE.open("wb") as file:
        logging.getLogger(__name__).info("Serialising the solved model")
        dump(
            solved_model,
            file,
            compress=("zlib", 0),
            protocol=pickle.HIGHEST_PROTOCOL,
        )
    return solved_model


# =============================================================================
# BASELINE CONSTRUCTION
# =============================================================================

def save_baseline_projections(
    baseline_projections: BaselineProjections,
) -> None:
    """Save the two stable, named baseline projection tables."""
    baseline_projections.charting_projections.to_csv(
        RESULTS_FOLDER / "baseline charting projections.csv"
    )
    baseline_projections.database_projections.to_csv(
        RESULTS_FOLDER / "baseline database projections.csv"
    )


if __name__ == "__main__":
    main()
